import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { Poppins } from "next/font/google";
import { ConditionalClientChrome } from "@/components/ConditionalClientChrome";
import { Toaster } from "react-hot-toast";
import { FirebaseAuthProvider } from "@/components/FirebaseAuthProvider";
import { LocationProvider } from "@/contexts/LocationContext";
import { CategoryProvider } from "@/contexts/CategoryContext";
import { FavoritesProvider } from "@/contexts/FavoritesContext";

const poppins = localFont({
  src: "../fonts/Poppins.woff2",
  variable: "--font-poppins",
  weight: "400",
  preload: false,
});

export const metadata: Metadata = {
  title: "Celeste ",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <FirebaseAuthProvider>
          <LocationProvider>
            <CategoryProvider>
              <FavoritesProvider>
              <ConditionalClientChrome>{children}</ConditionalClientChrome>
              <Toaster
                position="bottom-right"
                toastOptions={{
                  style: {
                    background: "#000000",
                    color: "#fff",
                  },
                }}
              />
              </FavoritesProvider>
            </CategoryProvider>
          </LocationProvider>
        </FirebaseAuthProvider>
      </body>
    </html>
  );
}
