steps:
  # Build the container image (NEXT_PUBLIC_* must be set at build time for client bundle)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}"
      - "--build-arg"
      - "NEXT_PUBLIC_GOOGLE_API_KEY=${_GOOGLE_MAPS_API_KEY}"
      - "."

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--timeout"
      - "300"
      - "--max-instances"
      - "10"

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}"

# Substitutions for configurable values
# Set _GOOGLE_MAPS_API_KEY in your Cloud Build trigger (or Secret Manager) - required for Maps/Places
substitutions:
  _SERVICE_NAME: "nextjs-web"
  _REGION: "asia-south1"
  _TAG: "latest"
  _GOOGLE_MAPS_API_KEY: ""

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: N1_HIGHCPU_8

timeout: 1200s

